# .travis.yml
# Configure Travis CI service to build SOCI library, http://github.com/SOCI
#
# Copyright (c) 2013 Mateusz Loskot <mateusz@loskot.net>
#
dist: trusty

sudo: required

language: cpp

compiler:
  - g++
  #- clang

services:
  - mysql
  - postgresql

env:
  global:
    - secure: "I7/28jg7R24y64426d5XsfILrd/VW0BdwFbNpEgBfW1qNk9GpkNGTvp/ET6hKwBVrW5jmN9QdEviGcPpQRIAlMj6g9GvZeAUxM+VZTcXD2u30REUPPxNTJMRVHPfL9DA7EMFCST8SjBCgMdTHFwqLV4vSQEF4NTXbntley/IPfM="

matrix:
  include:
    - env: SOCI_TRAVIS_BACKEND=db2
    - env: SOCI_TRAVIS_BACKEND=empty
    - env: SOCI_TRAVIS_BACKEND=firebird
    - env: SOCI_TRAVIS_BACKEND=mysql
    - env: SOCI_TRAVIS_BACKEND=odbc
    - env: SOCI_TRAVIS_BACKEND=postgresql
    - env: SOCI_TRAVIS_BACKEND=sqlite3
    - env: SOCI_TRAVIS_BACKEND=valgrind
    - env: SOCI_TRAVIS_BACKEND=oracle WITH_BOOST=OFF

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
    coverity_scan:
        project:
            name: "SOCI/soci"
        notification_email: soci-devel@lists.sourceforge.net
        build_command_prepend: "mkdir build.cov; cd build.cov; cmake .."
        build_command: "make -j 4"
        branch_pattern: coverity_scan

before_install: ./scripts/travis/before_install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/000781732a3b1637ef82
    on_start: always
  irc:
    channels:
      - "irc.freenode.org#soci"
