# .travis.yml
# Configure Travis CI service to build SOCI library
# Mateusz Loskot <mateusz@loskot.net>, http://github.com/SOCI
#
language: cpp

# Testing against two compilers will create (at least) 2 rows in build matrix
# http://about.travis-ci.org/docs/user/languages/cpp/
compiler:
  - g++
  - clang

branches:
  only:
    - develop
    - master
    - /^release\/[0-9]\.[0-9]\.[0-9]$/

services:
  - mysql
  - postgresql

before_install: ./bin/ci/before_install.sh
before_script: ./bin/ci/before_script.sh
script: ./bin/ci/script.sh

notifications:
  email:
    recipients:
      - soci-devel@lists.sourceforge.net
      - mateusz@loskot.net
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

  irc:
    channels:
      - "irc.freenode.org#soci"
